# Application
quarkus.application.name=order-book
quarkus.http.port=8888

# PostgreSQL (producao/dev)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=orderbook
quarkus.datasource.password=orderbook
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:2345/orderbook

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

# Jackson
quarkus.jackson.serialization-inclusion=non-null

# OpenAPI / Swagger UI
quarkus.smallrye-openapi.info-title=Vibranium Order Book API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API para negociacao de Vibranium/BRL com Order Book, Matching Engine e Wallets
quarkus.swagger-ui.always-include=true
